### Listar usuários
GET http://localhost:8082/usuarios
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb2FvLnNpbHZhQGpicy5jb20uYnIiLCJpYXQiOjE3NjA2OTcwMjUsImV4cCI6MTc2MDY5NzkyNX0.iNIwtFqirqAEKaiQJ1FbnNyzNgLn-ZAWynekMkU1lrU

### Buscar usuário por ID
GET http://localhost:8082/usuarios/16
Accept: application/json


### Criar usuário
POST http://localhost:8082/usuarios
Content-Type: application/json
Accept: application/json

{
  "nome": "Maria Silva",
  "cpf": "12345678901",
  "senha": "minhasenha",
  "email": "maria.silva@example.com",
  "idUsuarioTipo": 1,
  "idEstrutura": 1
}

### Atualizar usuário
PUT http://localhost:8082/usuarios/16
Content-Type: application/json
Accept: application/json

{
  "nome": "Maria Oliveira Silva"
}

### Deletar usuário
DELETE http://localhost:8082/usuarios/16

### Login
POST http://localhost:8082/auth/login
Content-Type: application/json

{
  "username": "hermione.granger@hotmail.com",
  "password": "senha"
}

### Logout
POST http://localhost:8082/auth/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImJydW5hLmxpbWFAamJzLmNvbS5iciIsInN1YiI6ImJydW5hLmxpbWFAamJzLmNvbS5icnxSSCIsImlhdCI6MTc2MTc0NzQxNywiZXhwIjoxNzYyMzUyMjE3fQ.8OmFxo9DBd-T1Q_NVHSbbSPCTTymE6MLl-hqATKj1W0"
}

### Hierarquia de Usuários (buscar abaixo)
GET http://localhost:8082/usuarios/hierarquia/18?orientacao=ABAIXO
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZF91c3VhcmlvIjoyOCwiaWRfZXN0cnV0dXJhIjoxLCJpZF90aXBvX3VzdWFyaW8iOjEsInVzZXJuYW1lIjoiaGVybWlvbmUuZ3JhbmdlckBob3RtYWlsLmNvbSIsInN1YiI6Imhlcm1pb25lLmdyYW5nZXJAaG90bWFpbC5jb218RElSRVRPUiIsImlhdCI6MTc2MjEyNTIwMywiZXhwIjoxNzYyMTI2MTAzfQ.0q4DB5DmL25eKnso0_VIlBi4KXrxoYVr1IxqsBJ3SRE
Accept: application/json

### Hierarquia de Usuários (buscar acima)
GET http://localhost:8082/usuarios/hierarquia/18?orientacao=ACIMA
Authorization: Bearer {{token}}
Accept: application/json

### Get Perfil
GET http://localhost:8082/usuarios/perfil
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZF91c3VhcmlvIjoyOCwiaWRfZXN0cnV0dXJhIjoxLCJpZF90aXBvX3VzdWFyaW8iOjEsInVzZXJuYW1lIjoiaGVybWlvbmUuZ3JhbmdlckBob3RtYWlsLmNvbSIsInN1YiI6Imhlcm1pb25lLmdyYW5nZXJAaG90bWFpbC5jb218RElSRVRPUiIsImlhdCI6MTc2MjQ0ODM0NywiZXhwIjoxNzYyNDQ5MjQ3fQ.9nZMuWPoGWh-QOYyDzbFXhhqtCzTxl0IA765lsmOSkc
Accept: application/json

